// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import "context"

type Registrar interface{}

type HealthRequest struct{}

type HealthResponse struct {
	Status string
}

type EchoServiceServer interface {
	Ping(ctx context.Context, req *PingRequest) (*PingResponse, error)
	Health(ctx context.Context, req *HealthRequest) (*HealthResponse, error)
}

func RegisterEchoServiceServer(_ Registrar, _ EchoServiceServer) {}
