// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

type Registrar interface{}

type MethodDesc struct {
	MethodName string
}

type ServiceDesc struct {
	ServiceName string
	HandlerType any
	Methods     []MethodDesc
}

type EchoServiceServer interface {
	Ping(*PingRequest) *PingResponse
	Health() string
}

func RegisterEchoServiceServer(_ Registrar, _ EchoServiceServer) {}

var EchoService_ServiceDesc = ServiceDesc{
	ServiceName: "example.echo.v1.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []MethodDesc{
		{MethodName: "ping"},
		{MethodName: "Health"},
	},
}
