package grpc

import (
	"os"
	"path/filepath"
	"testing"

	"gopkg.inshopline.com/bff/go-analyzer/internal/facts"
	"gopkg.inshopline.com/bff/go-analyzer/internal/project"
)

func TestBuildCatalogMapsGeneratedUnaryLegacyAndStreamingMethods(t *testing.T) {
	dir := t.TempDir()
	writeGeneratedFile(t, dir, "modern.go", `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package proto
const Order_Get_FullMethodName = "/shop.order.v1.OrderService/Get"
type OrderServiceClient interface { Get() }
type orderServiceClient struct { cc any }
func NewOrderServiceClient(cc any) OrderServiceClient { return &orderServiceClient{cc: cc} }
func (c *orderServiceClient) Get() { c.cc.Invoke(nil, Order_Get_FullMethodName, nil, nil) }
`)
	writeGeneratedFile(t, dir, "legacy.go", `// Code generated by protoc-gen-go. DO NOT EDIT.
package proto
type LegacyClient interface { Search() }
type legacyClient struct { cc any }
func NewLegacyClient(cc any) LegacyClient { return &legacyClient{cc: cc} }
func (c *legacyClient) Search() { c.cc.Invoke(nil, "/shop.order.v1.LegacyService/search", nil, nil) }
`)
	writeGeneratedFile(t, dir, "stream.go", `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package proto
var Order_ServiceDesc = grpc.ServiceDesc{Streams: []grpc.StreamDesc{{ServerStreams: true}}}
type StreamClient interface { Watch() }
type streamClient struct { cc any }
func NewStreamClient(cc any) StreamClient { return &streamClient{cc: cc} }
func (c *streamClient) Watch() { c.cc.NewStream(nil, &Order_ServiceDesc.Streams[0], "/shop.order.v1.OrderService/Watch") }
`)

	catalog, err := BuildCatalog([]project.DependencyPackage{{ImportPath: "example.com/proto", Dir: dir, GoFiles: []string{"stream.go", "legacy.go", "modern.go"}}})
	if err != nil {
		t.Fatal(err)
	}
	if len(catalog.Operations) != 3 {
		t.Fatalf("operations = %#v", catalog.Operations)
	}
	entry, ok := catalog.Lookup(BindingKey{GoPackage: "example.com/proto", ClientType: "OrderServiceClient", GoMethod: "Get"})
	if !ok || entry.Operation.FullMethod != "/shop.order.v1.OrderService/Get" || entry.Operation.StreamingMode != facts.GrpcStreamingUnary {
		t.Fatalf("modern entry = %#v, ok=%v", entry, ok)
	}
	entry, ok = catalog.Lookup(BindingKey{GoPackage: "example.com/proto", ClientType: "LegacyClient", GoMethod: "Search"})
	if !ok || entry.Operation.FullMethod != "/shop.order.v1.LegacyService/search" {
		t.Fatalf("legacy entry = %#v, ok=%v", entry, ok)
	}
	entry, ok = catalog.Lookup(BindingKey{GoPackage: "example.com/proto", ClientType: "StreamClient", GoMethod: "Watch"})
	if !ok || entry.Operation.StreamingMode != facts.GrpcStreamingServer {
		t.Fatalf("stream entry = %#v, ok=%v", entry, ok)
	}
}

func writeGeneratedFile(t *testing.T, root, name, source string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, name), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
}
