package grpc

import (
	"os"
	"path/filepath"
	"testing"

	"gopkg.inshopline.com/bff/go-analyzer/internal/astindex"
	"gopkg.inshopline.com/bff/go-analyzer/internal/facts"
	"gopkg.inshopline.com/bff/go-analyzer/internal/project"
)

// TestExtractServerProvidersSkipsAmbiguousRegistrationWithoutAffectingOthers
// verifies that a gRPC server registration whose implementation resolves to
// more than one concrete type produces zero provider facts (there is no
// generated method list to fall back on once the implementation itself can't
// be pinned down) plus a ServerBindingIssue explaining why — while every
// other, unambiguous registration in the same project is still fully
// resolved and unaffected.
func TestExtractServerProvidersSkipsAmbiguousRegistrationWithoutAffectingOthers(t *testing.T) {
	root := t.TempDir()
	writeServerExtractorFile(t, root, "go.mod", "module example.com/ambiguous\n\ngo 1.24\n")
	writeServerExtractorFile(t, root, "pb/foo_grpc.pb.go", `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package pb

import (
	"context"

	"google.golang.org/grpc"
)

type FooServer interface {
	Do(ctx context.Context, req *DoRequest) (*DoResponse, error)
}
type DoRequest struct{}
type DoResponse struct{}

func RegisterFooServer(s grpc.ServiceRegistrar, srv FooServer) {
	s.RegisterService(&Foo_ServiceDesc, srv)
}

var Foo_ServiceDesc = grpc.ServiceDesc{ServiceName: "example.Foo", HandlerType: (*FooServer)(nil)}

type BarServer interface {
	Ping(ctx context.Context, req *PingRequest) (*PingResponse, error)
}
type PingRequest struct{}
type PingResponse struct{}

func RegisterBarServer(s grpc.ServiceRegistrar, srv BarServer) {
	s.RegisterService(&Bar_ServiceDesc, srv)
}

var Bar_ServiceDesc = grpc.ServiceDesc{ServiceName: "example.Bar", HandlerType: (*BarServer)(nil)}
`)
	writeServerExtractorFile(t, root, "biz/impl.go", `package biz

import (
	"context"

	"example.com/ambiguous/pb"
)

type ImplA struct{}

func (a *ImplA) Do(ctx context.Context, req *pb.DoRequest) (*pb.DoResponse, error) { return nil, nil }

type ImplB struct{}

func (b *ImplB) Do(ctx context.Context, req *pb.DoRequest) (*pb.DoResponse, error) { return nil, nil }

type BarImpl struct{}

func (b *BarImpl) Ping(ctx context.Context, req *pb.PingRequest) (*pb.PingResponse, error) {
	return nil, nil
}
`)
	writeServerExtractorFile(t, root, "app/register.go", `package app

import (
	"example.com/ambiguous/biz"
	"example.com/ambiguous/pb"

	"google.golang.org/grpc"
)

// NewFoo has two return branches proving two different concrete
// implementations: the analyzer cannot statically tell which one a given
// call site ends up with, so RegisterFooServer below is genuinely ambiguous.
func NewFoo(useA bool) pb.FooServer {
	if useA {
		return &biz.ImplA{}
	}
	return &biz.ImplB{}
}

func RegisterAll(s grpc.ServiceRegistrar) {
	pb.RegisterFooServer(s, NewFoo(true))
	pb.RegisterBarServer(s, &biz.BarImpl{})
}
`)

	p, err := project.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	idx, err := astindex.Build(p)
	if err != nil {
		t.Fatal(err)
	}
	_, providers, issues := ExtractServerProviders(p, idx)

	if len(issues) != 1 {
		t.Fatalf("issues = %#v, want exactly 1 ambiguous issue", issues)
	}
	if issues[0].Kind != ServerBindingAmbiguous || issues[0].RegisterFunction != "RegisterFooServer" {
		t.Fatalf("issue = %#v, want ambiguous RegisterFooServer", issues[0])
	}

	var fooFound, barFound bool
	var barImplementation string
	for _, provider := range providers {
		switch provider.RegisterFunction {
		case "RegisterFooServer":
			fooFound = true
		case "RegisterBarServer":
			barFound = true
			barImplementation = provider.ImplementationType
		}
	}
	if fooFound {
		t.Fatal("ambiguous registration must not produce any provider facts — there is no method list independent of the implementation")
	}
	if !barFound {
		t.Fatal("expected a provider fact for the unrelated RegisterBarServer registration")
	}
	if barImplementation != "BarImpl" {
		t.Fatalf("unrelated registration must still resolve its implementation, got %q", barImplementation)
	}
}

func TestExtractServerProvidersResolvesGenericContainerRegistration(t *testing.T) {
	root := t.TempDir()
	writeContainerRegistrationProject(t, root, `
func RegisterAll(s api.Registrar) {
	try.Check(container.Provide(provider.NewEchoServer))
	api.RegisterEchoServiceServer(s, container.GetBean[api.EchoServiceServer]().MustGet())
}
`)

	providers, issues := extractContainerRegistrationProviders(t, root)
	if len(issues) != 0 {
		t.Fatalf("issues = %#v, want none", issues)
	}
	if len(providers) != 2 {
		t.Fatalf("providers = %#v, want 2", providers)
	}
	for _, provider := range providers {
		if provider.ImplementationType != "EchoServer" {
			t.Fatalf("implementation type = %q, want EchoServer", provider.ImplementationType)
		}
		if provider.HandlerSymbol == "" {
			t.Fatalf("handler symbol must be resolved: %#v", provider)
		}
	}
}

func TestExtractServerProvidersKeepsGenericContainerAmbiguity(t *testing.T) {
	root := t.TempDir()
	writeContainerRegistrationProject(t, root, `
func RegisterAll(s api.Registrar) {
	try.Check(container.Provide(provider.NewEchoServer))
	try.Check(container.Provide(provider.NewAlternativeEchoServer))
	api.RegisterEchoServiceServer(s, container.GetBean[api.EchoServiceServer]().MustGet())
}
`)

	providers, issues := extractContainerRegistrationProviders(t, root)
	if len(issues) != 1 || issues[0].Kind != ServerBindingAmbiguous {
		t.Fatalf("issues = %#v, want one ambiguous issue", issues)
	}
	if len(providers) != 0 {
		t.Fatalf("providers = %#v, ambiguous container registration must produce no provider facts", providers)
	}
}

func TestExtractServerProvidersIgnoresConditionalContainerRegistration(t *testing.T) {
	root := t.TempDir()
	writeContainerRegistrationProject(t, root, `
func RegisterAll(s api.Registrar, enabled bool) {
	if enabled {
		try.Check(container.Provide(provider.NewEchoServer))
	}
	api.RegisterEchoServiceServer(s, container.GetBean[api.EchoServiceServer]().MustGet())
}
`)

	providers, issues := extractContainerRegistrationProviders(t, root)
	if len(issues) != 1 || issues[0].Kind != ServerBindingUnresolved {
		t.Fatalf("issues = %#v, want one unresolved issue", issues)
	}
	if len(providers) != 0 {
		t.Fatalf("providers = %#v, conditional container registration must produce no provider facts", providers)
	}
}

func TestExtractServerProvidersIgnoresContainerRegistrationAfterServerRegistration(t *testing.T) {
	root := t.TempDir()
	writeContainerRegistrationProject(t, root, `
func RegisterAll(s api.Registrar) {
	api.RegisterEchoServiceServer(s, container.GetBean[api.EchoServiceServer]().MustGet())
	try.Check(container.Provide(provider.NewEchoServer))
}
`)

	providers, issues := extractContainerRegistrationProviders(t, root)
	if len(issues) != 1 || issues[0].Kind != ServerBindingUnresolved {
		t.Fatalf("issues = %#v, want one unresolved issue", issues)
	}
	if len(providers) != 0 {
		t.Fatalf("providers = %#v, late container registration must produce no provider facts", providers)
	}
}

func TestExtractServerProvidersIgnoresContainerFactoryWithUnknownReturnPath(t *testing.T) {
	root := t.TempDir()
	writeContainerRegistrationProject(t, root, `
func RegisterAll(s api.Registrar) {
	try.Check(container.Provide(provider.NewUncertainEchoServer))
	api.RegisterEchoServiceServer(s, container.GetBean[api.EchoServiceServer]().MustGet())
}
`)

	providers, issues := extractContainerRegistrationProviders(t, root)
	if len(issues) != 1 || issues[0].Kind != ServerBindingUnresolved {
		t.Fatalf("issues = %#v, want one unresolved issue", issues)
	}
	if len(providers) != 0 {
		t.Fatalf("providers = %#v, container factory with unknown return path must produce no provider facts", providers)
	}
}

func extractContainerRegistrationProviders(t *testing.T, root string) ([]facts.GrpcProviderFact, []ServerBindingIssue) {
	t.Helper()
	p, err := project.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	idx, err := astindex.Build(p)
	if err != nil {
		t.Fatal(err)
	}
	_, providers, issues := ExtractServerProviders(p, idx)
	return providers, issues
}

func writeContainerRegistrationProject(t *testing.T, root, registration string) {
	t.Helper()
	writeServerExtractorFile(t, root, "go.mod", "module example.com/container\n\ngo 1.24\n")
	writeServerExtractorFile(t, root, "api/echo_grpc.pb.go", `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package api

import "context"

type Registrar interface{}

type EchoServiceServer interface {
	Ping(ctx context.Context, req *PingRequest) (*PingResponse, error)
	Health(ctx context.Context, req *HealthRequest) (*HealthResponse, error)
}
type PingRequest struct{}
type PingResponse struct{}
type HealthRequest struct{}
type HealthResponse struct{}

func RegisterEchoServiceServer(_ Registrar, _ EchoServiceServer) {}
`)
	writeServerExtractorFile(t, root, "provider/echo.go", `package provider

import (
	"context"

	"example.com/container/api"
)

type EchoServer struct{}

func NewEchoServer() api.EchoServiceServer { return &EchoServer{} }
func (EchoServer) Ping(ctx context.Context, req *api.PingRequest) (*api.PingResponse, error) {
	return nil, nil
}
func (EchoServer) Health(ctx context.Context, req *api.HealthRequest) (*api.HealthResponse, error) {
	return nil, nil
}

type AlternativeEchoServer struct{}

func NewAlternativeEchoServer() api.EchoServiceServer { return &AlternativeEchoServer{} }
func (AlternativeEchoServer) Ping(ctx context.Context, req *api.PingRequest) (*api.PingResponse, error) {
	return nil, nil
}
func (AlternativeEchoServer) Health(ctx context.Context, req *api.HealthRequest) (*api.HealthResponse, error) {
	return nil, nil
}

func NewUncertainEchoServer(enabled bool) api.EchoServiceServer {
	if enabled {
		return &EchoServer{}
	}
	return nil
}
`)
	writeServerExtractorFile(t, root, "app/register.go", `package app

import (
	"example.com/container/api"
	"example.com/container/provider"
	container "example.com/runtime/container"
	try "example.com/runtime/try"
)
`+registration)
}

func writeServerExtractorFile(t *testing.T, root, relPath, content string) {
	t.Helper()
	full := filepath.Join(root, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
